// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ImportFilterList() {
  return window['go']['files']['FileImport']['ImportFilterList']();
}

export function Init(arg1, arg2) {
  return window['go']['files']['FileImport']['Init'](arg1, arg2);
}
