// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportFilterList() {
  return window['go']['files']['Files']['ExportFilterList']();
}

export function ImportFilterList() {
  return window['go']['files']['Files']['ImportFilterList']();
}

export function Init(arg1, arg2) {
  return window['go']['files']['Files']['Init'](arg1, arg2);
}
