// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {cfg} from '../models';

export function ExportFilterList():Promise<void>;

export function Init(arg1:context.Context,arg2:cfg.Config):Promise<void>;
