// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFilterList(arg1) {
  return window['go']['cfg']['Config']['AddFilterList'](arg1);
}

export function GetCAInstalled() {
  return window['go']['cfg']['Config']['GetCAInstalled']();
}

export function GetFilterLists() {
  return window['go']['cfg']['Config']['GetFilterLists']();
}

export function GetPort() {
  return window['go']['cfg']['Config']['GetPort']();
}

export function GetVersion() {
  return window['go']['cfg']['Config']['GetVersion']();
}

export function Lock() {
  return window['go']['cfg']['Config']['Lock']();
}

export function RLock() {
  return window['go']['cfg']['Config']['RLock']();
}

export function RLocker() {
  return window['go']['cfg']['Config']['RLocker']();
}

export function RUnlock() {
  return window['go']['cfg']['Config']['RUnlock']();
}

export function RemoveFilterList(arg1) {
  return window['go']['cfg']['Config']['RemoveFilterList'](arg1);
}

export function RunMigrations() {
  return window['go']['cfg']['Config']['RunMigrations']();
}

export function Save() {
  return window['go']['cfg']['Config']['Save']();
}

export function SetCAInstalled(arg1) {
  return window['go']['cfg']['Config']['SetCAInstalled'](arg1);
}

export function SetPort(arg1) {
  return window['go']['cfg']['Config']['SetPort'](arg1);
}

export function ToggleFilterList(arg1, arg2) {
  return window['go']['cfg']['Config']['ToggleFilterList'](arg1, arg2);
}

export function TryLock() {
  return window['go']['cfg']['Config']['TryLock']();
}

export function TryRLock() {
  return window['go']['cfg']['Config']['TryRLock']();
}

export function Unlock() {
  return window['go']['cfg']['Config']['Unlock']();
}
