name: Bug Report
description: Report a bug in Zen
type: Bug
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug in Zen.
        Before submitting this issue, please search the [issue tracker](https://github.com/ZenPrivacy/zen-desktop/issues?q=is%3Aissue) to see if it has already been reported.
        Please fill out the information below to help us reproduce and fix the issue you are experiencing.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Describe the bug you are experiencing in as much detail as possible.
        Attach screenshots or videos if it helps explain the issue.
        In case you are proficient with using the command line, and use macOS or Linux, please include the logs that Zen prints out ([read how to locate the binaries on our wiki](https://github.com/ZenPrivacy/zen-desktop/wiki/How-to-find-Zen's-binaries)).
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: |
        What version of Zen are you using? It can be found on the bottom of the "Settings" page.
      placeholder: v0.0.0
    validations:
      required: true
  - type: input
    id: os-kind
    attributes:
      label: Operating System
      description: |
        What operating system and version number are you using? If you are using Linux, please include the distribution.
      placeholder: Windows 10
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: |
        If you are able to reproduce the bug consistently, please include the steps to reproduce it.
      placeholder: |
        1. Open the app
        2. Click on the "Start" button
        3 ...
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any additional information that might be relevant to the issue.
      placeholder: |
        Are you using any other tunnels, proxies or VPNs? Are you using any antivirus software? Which apps or websites seem to be affected?
    validations:
      required: false
