// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearCache() {
  return window['go']['certmanager']['CertManager']['ClearCache']();
}

export function GetCertificate(arg1) {
  return window['go']['certmanager']['CertManager']['GetCertificate'](arg1);
}

export function Init() {
  return window['go']['certmanager']['CertManager']['Init']();
}

export function ScheduleCacheCleanup(arg1, arg2) {
  return window['go']['certmanager']['CertManager']['ScheduleCacheCleanup'](arg1, arg2);
}

export function UninstallCA() {
  return window['go']['certmanager']['CertManager']['UninstallCA']();
}
