// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCertificate(arg1) {
  return window['go']['certmanager']['CertManager']['GetCertificate'](arg1);
}

export function Init() {
  return window['go']['certmanager']['CertManager']['Init']();
}

export function PurgeCache() {
  return window['go']['certmanager']['CertManager']['PurgeCache']();
}

export function UninstallCA() {
  return window['go']['certmanager']['CertManager']['UninstallCA']();
}
