// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {tls} from '../models';

export function GetCertificate(arg1:string):Promise<tls.Certificate>;

export function Init():Promise<void>;

export function PurgeCache():Promise<void>;

export function UninstallCA():Promise<string>;
