// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {tls} from '../models';
import {time} from '../models';

export function ClearCache():Promise<void>;

export function GetCertificate(arg1:string):Promise<tls.Certificate>;

export function Init():Promise<void>;

export function ScheduleCacheCleanup(arg1:string,arg2:time.Time):Promise<void>;

export function UninstallCA():Promise<string>;
