// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function AddFilterList(arg1:config.filterList):Promise<string>;

export function GetFilterLists():Promise<Array<config.filterList>>;

export function GetPort():Promise<number>;

export function GetVersion():Promise<string>;

export function RemoveFilterList(arg1:string):Promise<string>;

export function Save():Promise<void>;

export function SetPort(arg1:number):Promise<string>;

export function ToggleFilterList(arg1:string,arg2:boolean):Promise<string>;
