// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFilterList(arg1) {
  return window['go']['config']['config']['AddFilterList'](arg1);
}

export function GetFilterLists() {
  return window['go']['config']['config']['GetFilterLists']();
}

export function GetPort() {
  return window['go']['config']['config']['GetPort']();
}

export function GetVersion() {
  return window['go']['config']['config']['GetVersion']();
}

export function RemoveFilterList(arg1) {
  return window['go']['config']['config']['RemoveFilterList'](arg1);
}

export function Save() {
  return window['go']['config']['config']['Save']();
}

export function SetPort(arg1) {
  return window['go']['config']['config']['SetPort'](arg1);
}

export function ToggleFilterList(arg1, arg2) {
  return window['go']['config']['config']['ToggleFilterList'](arg1, arg2);
}
