// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenLogsFolder() {
  return window['go']['app']['App']['OpenLogsFolder']();
}

export function SetupLogger() {
  return window['go']['app']['App']['SetupLogger']();
}

export function StartProxy() {
  return window['go']['app']['App']['StartProxy']();
}

export function StopProxy() {
  return window['go']['app']['App']['StopProxy']();
}

export function UninstallCA() {
  return window['go']['app']['App']['UninstallCA']();
}
