// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenLogsDirectory():Promise<void>;

export function StartProxy():Promise<void>;

export function StopProxy():Promise<void>;

export function UninstallCA():Promise<void>;
