// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportCustomFilterLists() {
  return window['go']['app']['App']['ExportCustomFilterLists']();
}

export function ImportCustomFilterLists() {
  return window['go']['app']['App']['ImportCustomFilterLists']();
}

export function IsNoSelfUpdate() {
  return window['go']['app']['App']['IsNoSelfUpdate']();
}

export function OpenLogsDirectory() {
  return window['go']['app']['App']['OpenLogsDirectory']();
}

export function StartProxy() {
  return window['go']['app']['App']['StartProxy']();
}

export function StopProxy() {
  return window['go']['app']['App']['StopProxy']();
}

export function UninstallCA() {
  return window['go']['app']['App']['UninstallCA']();
}
