// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Disable():Promise<void>;

export function Enable():Promise<void>;

export function IsEnabled():Promise<boolean>;
